// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCL2G0xiZ9TYdtnS2O_LpttpRWlipaa6E',
    appId: '1:260934787549:web:a649e0d5e513f85fe25634',
    messagingSenderId: '260934787549',
    projectId: 'fir-2-a22c1',
    authDomain: 'fir-2-a22c1.firebaseapp.com',
    storageBucket: 'fir-2-a22c1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADEvnGt1ai1kayUWerwkkdPK_A36BSXIk',
    appId: '1:260934787549:android:c542f5418ff9dad7e25634',
    messagingSenderId: '260934787549',
    projectId: 'fir-2-a22c1',
    storageBucket: 'fir-2-a22c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjGKMLoEfkRzk8rNf3FLtGTDlFkjNtRGY',
    appId: '1:260934787549:ios:34e68b343e402049e25634',
    messagingSenderId: '260934787549',
    projectId: 'fir-2-a22c1',
    storageBucket: 'fir-2-a22c1.appspot.com',
    iosBundleId: 'com.example.flutterApplication4',
  );
}
